apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: microcert-view-infrastructure
  namespace: microcert
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: microcert-view-infrastructure
subjects:
- kind: ServiceAccount
  name: default
  namespace: microcert
