apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: microcert-view-infrastructure
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - infrastructures
  verbs:
  - get
